#include "hap_bct_http_handlers.h"
#include "hap_fw_upgrade.h"
#include "hap_platform_keystore.h"
#include "hap_platform_memory.h"
#include "hap_platform_httpd.h"
#include "esp_mfi_aes.h"
#include "esp_mfi_base64.h"
#include "esp_mfi_i2c.h"
#include "esp_mfi_sha.h"
#include "esp_mfi_rand.h"
#include "hap_platform_os.h"
#include "hap_apple_chars.h"
#include "hap_apple_servs.h"
#include "hap.h"
#include "hap_wac.h"
#include "hap_bct.h"
#include "hkdf-sha.h"
#include "iot_button.h"

#include "app_wifi.h"
#include "app_hap_setup_payload.h"
#include "qrcode.h"

#include "freertos/FreeRTOS.h"
#include "freertos/FreeRTOSConfig.h"
#include "freertos/task.h"
#include "freertos/queue.h"
